### ISSUE TITLE
Create dockerfile for project

### ISSUE THREAD

**Issue by gonzalomcruz** [gonzalomcruz/mpi#3]
Migrate current development environment from Vagrant to Docker.
- remove Vagrantfile
- create simple Dockerfile which installs apt packages and pip requirements.

**Comment by ghost** [comment]
Taking this!. What kind of docker file do you need? only the build environment? or a container which builds the binaries inside and lets user access them by attaching a shell?

**Comment by gonzalomcruz** [comment]
Hi! Just merged your pull request with the basic dockerfile. It would be great to have a dockerfile that builds the examples,  if you want to work on this I can open a new issue for it.
